@host = https://localhost:5001/api/absen


####

POST {{host}} HTTP/1.1
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImZjZjliOTQ1LWZiMWUtNDBlNS1hNzE1LWY1NzZlNGJlNDU0ZCIsIm5hbWUiOiIxMjM0NTciLCJyb2xlIjoia2FyeWF3YW4iLCJuYmYiOjE1OTk2ODU0MjYsImV4cCI6MTYwMDI5MDIyNSwiaWF0IjoxNTk5Njg1NDI2fQ.Pk3Kt5wQCSUA24zwoZqw6FBKaMhJGNIQZz0x_jQl7uQ

  {
    "idabsen": 0,
    "idKaryawan": 1,
    "absenType": "Lembur",
    "masuk": "2020-08-21",
    "pulang": null,
    "karyawanId": 1,
  }


####

