@host = https://localhost:5001/api/jenispelanggaran


####

GET {{host}} HTTP/1.1
Content-Type: application/json

####

POST {{host}} HTTP/1.1
Content-Type: application/json

 {
    "idlevel": 1,
    "jenispelanggaran": "Berat",
    "pengurangankaryawan": 10,
    "penguranganperusahaan": 11,
    "penambahanpoint": 12
 }

#####

PUT  {{host}}/1 HTTP/1.1
Content-Type: application/json

{
    "idjenispelanggaran": 2,
    "idlevel": 1,
    "jenispelanggaran": "Tidak Pake Helm",
    "pengurangankaryawan": 11,
    "penguranganperusahaan": 11,
    "penambahanpoint": 11
  }


####

Delete {{host}}/2 HTTP/1.1
Content-Type: application/json
#####