@host = https://localhost:5001/api/karyawan


####

GET {{host}} HTTP/1.1
Content-Type: application/json


####

POST {{host}} HTTP/1.1
Content-Type: application/json

{
    "Id": 0,
    "kodekaryawan": 123456,
    "perusahaanid": 1,
    "namakaryawan": "Aji Latuperisa",
    "jabatan": "Driver",
    "alamat": null,
    "kontak": null,
    "email": null,
    "userid": null, 
    "perusahaanKaryawan":{
        "jabatan":"Manager",
        "mulaiKerja":"2020-08-1-1",
        "selesaiKerja":null,
        "KaryawanId": 1,
        "PerusahaanId": 1,

    }
 }

####

PUT {{host}}/1 HTTP/1.1
Content-Type: application/json

{
    "idkaryawan": 0,
    "idperusahaan": 1,
    "namakaryawan": "Aji Latuperisa",
    "jabatan": "Driver",
    "alamat": null,
    "kontak": null,
    "email": null,
    "userid": null
 }


#####


Delete {{host}}/3 HTTP/1.1
Content-Type: application/json

#####