@host =https://36.94.6.214/api/periode


####

GET {{host}} HTTP/1.1
Content-Type: application/json

####

POST {{host}} HTTP/1.1
Content-Type: application/json

 {
    "idlevel": 0,
    "level": "Berat"
 }

#####

PUT  {{host}}/1 HTTP/1.1
Content-Type: application/json

{
    "idlevel": 5,
    "level": "Berat"

  }



####

Delete {{host}}/3 HTTP/1.1
Content-Type: application/json
#####