@host = https://localhost:5001/api/perusahaan


####

GET {{host}} HTTP/1.1
Content-Type: application/json

####

POST {{host}} HTTP/1.1
Content-Type: application/json

 {
    "idperusahaan": 0,
    "namaperusahaan": "Catur Perkasa",
    "alamat": null,
    "direktur": "Deny Siregar",
    "kontakdirektur": null,
    "emaildirektur": null,
    "logo": "https://www.rd.com/wp-content/uploads/2017/09/01-shutterstock_476340928-Irina-Bg-1024x683.jpg"
  }

#####

PUT  {{host}}/1 HTTP/1.1
Content-Type: application/json

  {
    "idperusahaan": 1,
    "namaperusahaan": "Catur Perkasa II",
    "alamat": null,
    "direktur": "Deny Siregar",
    "kontakdirektur": null,
    "emaildirektur": null,
    "logo": "https://www.rd.com/wp-content/uploads/2017/09/01-shutterstock_476340928-Irina-Bg-1024x683.jpg"
  }


####

Delete {{host}}/3 HTTP/1.1
Content-Type: application/json
#####