@host = https://localhost:5001/api/user


####

GET {{host}}/profile HTTP/1.1
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjE0NWUwMWZkLTliZWYtNGMyOS05NmE2LTM5NjQ4NTA3ZWNmYSIsIm5iZiI6MTU5ODg1MjcwNywiZXhwIjoxNTk5NDU3NTA3LCJpYXQiOjE1OTg4NTI3MDd9.KTZIpxyE1-USFIhY6xLIbpH_ci5M0FC8MfjZlaRO5C8

####

POST {{host}}/login HTTP/1.1
Content-Type: application/json

 {
    "Username": "Administrator",
    "password": "Administrator123#"
  }

#####